const demoListings = [
  {
    id: "demo-jerusalem-1",
    title: "חדר בדירת שותפים ליד האוניברסיטה העברית",
    city: "ירושלים",
    neighborhood: "רחביה",
    price: 2450,
    size_sqm: 18,
    balcony: true,
    floor: 2,
    parking: false,
    elevator: true,
    furnished: true,
    roommates: 2,
    smoking_allowed: false,
    campus: "האוניברסיטה העברית - גבעת רם",
    distance_to_campus_minutes: 14,
    distance_to_bus_minutes: 3,
    distance_to_train_minutes: 11,
    near_public_transportation: true,
    description: "דירת סטודנטים מוארת עם סלון משותף, מטבח מאובזר ותחבורה נוחה לקמפוס."
  },
  {
    id: "demo-tel-aviv-1",
    title: "דירת 2 חדרים ליד אוניברסיטת תל אביב",
    city: "תל אביב",
    neighborhood: "רמת אביב",
    price: 5200,
    size_sqm: 45,
    balcony: false,
    floor: 3,
    parking: true,
    elevator: true,
    furnished: false,
    roommates: 0,
    smoking_allowed: false,
    campus: "אוניברסיטת תל אביב",
    distance_to_campus_minutes: 12,
    distance_to_bus_minutes: 4,
    distance_to_train_minutes: 18,
    near_public_transportation: true,
    description: "דירה קטנה ושקטה לזוג או שני שותפים, קרובה לקווי אוטובוס מרכזיים."
  },
  {
    id: "demo-haifa-1",
    title: "חדר מרוהט לסטודנטים בטכניון",
    city: "חיפה",
    neighborhood: "נווה שאנן",
    price: 1900,
    size_sqm: 14,
    balcony: true,
    floor: 1,
    parking: false,
    elevator: false,
    furnished: true,
    roommates: 3,
    smoking_allowed: true,
    campus: "הטכניון",
    distance_to_campus_minutes: 9,
    distance_to_bus_minutes: 2,
    distance_to_train_minutes: 22,
    near_public_transportation: true,
    description: "חדר בדירה פעילה של סטודנטים, מתאים למי שמחפש מחיר נגיש וקרבה לקמפוס."
  }
];

module.exports = { demoListings };
