const demoListings = [
  {
    id: "demo-jerusalem-1",
    campus_id: "demo-hebrew-university",
    title: "חדר מואר ליד הר הצופים",
    description: "חדר בדירת שותפים שקטה, מתאים לסטודנטים. מודעת דמו בלבד.",
    listing_type: "room",
    city: "Jerusalem",
    neighborhood: "French Hill",
    street: "רחוב דמו 1",
    latitude: 31.7982,
    longitude: 35.2427,
    price: 2450,
    rooms: 1,
    floor: 2,
    size_sqm: 18,
    balcony: true,
    elevator: false,
    parking: false,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 0.9,
    nearest_bus_station: "תחנת הגבעה הצרפתית",
    distance_to_bus_station_m: 180,
    nearest_train_station: "רכבת קלה גבעת המבתר",
    distance_to_train_station_km: 2.4,
    status: "active"
  },
  {
    id: "demo-jerusalem-2",
    campus_id: "demo-hebrew-university",
    title: "דירת שני חדרים קרובה לקמפוס",
    description: "דירה קטנה ומסודרת עם תחבורה נוחה. נתוני דמו בלבד.",
    listing_type: "apartment",
    city: "Jerusalem",
    neighborhood: "French Hill",
    street: "רחוב דמו 2",
    latitude: 31.796,
    longitude: 35.2389,
    price: 3900,
    rooms: 2,
    floor: 1,
    size_sqm: 42,
    balcony: false,
    elevator: false,
    parking: true,
    furnished: false,
    smoking_allowed: false,
    current_roommates_count: 0,
    distance_to_campus_km: 1.1,
    nearest_bus_station: "תחנת האצ\"ל",
    distance_to_bus_station_m: 120,
    nearest_train_station: "רכבת קלה גבעת המבתר",
    distance_to_train_station_km: 2.1,
    status: "active"
  },
  {
    id: "demo-tel-aviv-1",
    campus_id: "demo-tau",
    title: "חדר ברמת אביב ליד האוניברסיטה",
    description: "חדר מרוהט בדירת שותפים קרובה מאוד לקמפוס.",
    listing_type: "room",
    city: "Tel Aviv",
    neighborhood: "Ramat Aviv",
    street: "רחוב דמו 5",
    latitude: 32.1139,
    longitude: 34.8027,
    price: 3600,
    rooms: 1,
    floor: 4,
    size_sqm: 14,
    balcony: false,
    elevator: true,
    parking: false,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 0.7,
    nearest_bus_station: "תחנת חיים לבנון",
    distance_to_bus_station_m: 110,
    nearest_train_station: "תחנת אוניברסיטה",
    distance_to_train_station_km: 2.8,
    status: "active"
  },
  {
    id: "demo-haifa-1",
    campus_id: "demo-haifa",
    title: "חדר באחוזה קרוב לאוניברסיטת חיפה",
    description: "חדר שקט עם נוף, מתאים ללימודים.",
    listing_type: "room",
    city: "Haifa",
    neighborhood: "Ahuza",
    street: "רחוב דמו 8",
    latitude: 32.777,
    longitude: 35.0003,
    price: 2200,
    rooms: 1,
    floor: 1,
    size_sqm: 15,
    balcony: true,
    elevator: false,
    parking: true,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 2.1,
    nearest_bus_station: "תחנת חורב",
    distance_to_bus_station_m: 160,
    nearest_train_station: "מרכזית חוף הכרמל",
    distance_to_train_station_km: 4.2,
    status: "active"
  },
  {
    id: "demo-beer-sheva-1",
    campus_id: "demo-bgu",
    title: "חדר בשכונה ג ליד בן גוריון",
    description: "חדר בדירת שותפים ליד הקמפוס וסורוקה.",
    listing_type: "room",
    city: "Be'er Sheva",
    neighborhood: "Gimel",
    street: "רחוב דמו 11",
    latitude: 31.2628,
    longitude: 34.7999,
    price: 1900,
    rooms: 1,
    floor: 1,
    size_sqm: 12,
    balcony: false,
    elevator: false,
    parking: false,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 0.5,
    nearest_bus_station: "תחנת רגר",
    distance_to_bus_station_m: 70,
    nearest_train_station: "באר שבע צפון אוניברסיטה",
    distance_to_train_station_km: 1.4,
    status: "active"
  },
  {
    id: "demo-ramat-gan-1",
    campus_id: "demo-bar-ilan",
    title: "חדר בגבעת שמואל ליד בר אילן",
    description: "חדר מרוהט בדירה נקייה עם שותפים שקטים.",
    listing_type: "room",
    city: "Ramat Gan",
    neighborhood: "Givat Shmuel",
    street: "רחוב דמו 14",
    latitude: 32.075,
    longitude: 34.8493,
    price: 2800,
    rooms: 1,
    floor: 4,
    size_sqm: 14,
    balcony: false,
    elevator: true,
    parking: false,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 0.9,
    nearest_bus_station: "תחנת גבעת שמואל",
    distance_to_bus_station_m: 100,
    nearest_train_station: "תחנת בני ברק",
    distance_to_train_station_km: 3,
    status: "active"
  },
  {
    id: "demo-ariel-1",
    campus_id: "demo-ariel",
    title: "חדר באריאל ליד האוניברסיטה",
    description: "חדר בדירה שקטה במרחק הליכה מהקמפוס.",
    listing_type: "room",
    city: "Ariel",
    neighborhood: "Ariel Center",
    street: "רחוב דמו 17",
    latitude: 32.1048,
    longitude: 35.2057,
    price: 1750,
    rooms: 1,
    floor: 2,
    size_sqm: 13,
    balcony: false,
    elevator: false,
    parking: true,
    furnished: true,
    smoking_allowed: false,
    current_roommates_count: 2,
    distance_to_campus_km: 0.6,
    nearest_bus_station: "תחנת אוניברסיטת אריאל",
    distance_to_bus_station_m: 120,
    nearest_train_station: "ראש העין צפון",
    distance_to_train_station_km: 12,
    status: "active"
  }
];

module.exports = { demoListings };
